server:
  port: 8181
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: core/shipping
          uri: http://localhost:8084
          predicates:
            - Path=/core/shipping/**
          filters:
            - StripPrefix=2
        - id: core/admin
          uri: http://localhost:8082
          predicates:
            - Path=/core/admin/**
          filters:
            - StripPrefix=2
        - id: core/pay
          uri: http://localhost:8083
          predicates:
            - Path=/core/pay/**
          filters:
            - StripPrefix=2
# eureka配置 客户端配置，注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
